feature: Add version to tool/patterns specification CY-2936
codacy/codacy-clang-tidy pull request #27
Opened 2020-09-25 14:53 UTC by franciscodua

2020-09-25 15:02 UTC, lolgab requested changes

2020-09-25 15:11 UTC, franciscodua commented on doc-generator/src/main/scala/Main.scala
> +    val pullProcess = Process(command = Seq("git", "pull"), cwd = Some(clangExtraDir.toJava))
Cool suggestion. Changed it ✅

2020-09-25 15:55 UTC, lolgab commented on doc-generator/src/main/scala/Main.scala
> +    val pullProcess = Process(command = Seq("git", "pull"), cwd = Some(clangExtraDir.toJava))
You need to `git reset --hard FETCH_HEAD` too, otherwise your just fetching the commit without checking out 👌

2020-09-25 16:30 UTC, franciscodua commented on doc-generator/src/main/scala/Main.scala
> +    val pullProcess = Process(command = Seq("git", "pull"), cwd = Some(clangExtraDir.toJava))
You're right. Didn't notice that one. Done

2020-09-26 14:45 UTC, lolgab approved these changes

2020-09-26 14:46 UTC, lolgab commented on doc-generator/src/main/scala/Main.scala
> +    val pullProcess = Process(command = Seq("git", "pull"), cwd = Some(clangExtraDir.toJava))
Thank you 🙏😊

2020-09-28 07:31 UTC, merged